# Generated by Django 2.2.6 on 2019-10-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_code', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.TextField()),
                ('city_name_en', models.TextField()),
                ('country_name', models.TextField()),
                ('country_name_en', models.TextField()),
                ('city_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dong',
            fields=[
                ('dong_code', models.IntegerField(primary_key=True, serialize=False)),
                ('dong_name', models.TextField()),
                ('dong_name_en', models.TextField()),
                ('gu_code', models.IntegerField()),
                ('gu_name', models.TextField()),
                ('gu_name_en', models.TextField()),
                ('city_code', models.IntegerField()),
                ('city_name', models.TextField()),
                ('city_name_en', models.TextField()),
                ('country_name', models.TextField()),
                ('country_name_en', models.TextField()),
                ('dong_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('gu_code', models.IntegerField(primary_key=True, serialize=False)),
                ('gu_name', models.TextField()),
                ('gu_name_en', models.TextField()),
                ('city_code', models.IntegerField()),
                ('city_name', models.TextField()),
                ('city_name_en', models.TextField()),
                ('country_name', models.TextField()),
                ('country_name_en', models.TextField()),
                ('gu_area', models.FloatField()),
            ],
        ),
    ]
