# Generated by Django 2.2.6 on 2019-10-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dong',
            name='dong_code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
